language: bash

services:
  - docker

addons:
  apt:
    packages:
    - libpam-cracklib

matrix:
  fast_finish: true

env:
  global:
    - IMAGE=essentialkaos/perfecto:centos7 SHELLCHECK_VERSION=0.7.1

before_install:
  - wget https://github.com/koalaman/shellcheck/releases/download/v${SHELLCHECK_VERSION}/shellcheck-v${SHELLCHECK_VERSION}.linux.x86_64.tar.xz
  - tar xf shellcheck-v${SHELLCHECK_VERSION}.linux.x86_64.tar.xz
  - mv shellcheck-v${SHELLCHECK_VERSION} shellcheck-latest
  - ./shellcheck-latest/shellcheck --version
  - docker pull "$IMAGE"
  - wget https://kaos.sh/perfecto/perfecto-docker
  - chmod +x perfecto-docker

script:
  - bash -c 'shopt -s globstar; ./shellcheck-latest/shellcheck install.sh'
  - bash -c 'shopt -s globstar; ./shellcheck-latest/shellcheck SOURCES/mkcryptpasswd'
  - bash .travis/script.sh
  - ./perfecto-docker mkcryptpasswd.spec
