name: CI

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master]

jobs:
  Bibop:
    name: Bibop
    runs-on: ubuntu-latest

    steps:
      - name: Install cracklib
        run: sudo apt-get install -y -qq libpam-cracklib

      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Run test recipes with Bibop
        uses: essentialkaos/bibop-action@v1
        with:
          path: SOURCES
          recipe: .bibop/mkcryptpasswd.recipe

  Perfecto:
    name: Perfecto
    runs-on: ubuntu-latest

    needs: Bibop

    steps:
      - name: Code checkout
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Check specs with Perfecto
        uses: essentialkaos/perfecto-action@v2
        with:
          files: mkcryptpasswd.spec

  Shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest

    needs: Bibop

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check scripts with Shellcheck
        uses: essentialkaos/shellcheck-action@v1
        with:
          files: SOURCES/mkcryptpasswd

  Typos:
    name: Typos
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check spelling
        uses: crate-ci/typos@master
