name: CI

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master]

jobs:
  Bibop:
    name: Bibop
    runs-on: ubuntu-latest

    steps:
      - name: Install cracklib
        run: sudo apt-get install -y -qq libpam-cracklib

      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Run test recipes with Bibop
        uses: essentialkaos/bibop-action@v1
        with:
          path: SOURCES
          recipe: .bibop/mkcryptpasswd.recipe

  Perfecto:
    name: Perfecto
    runs-on: ubuntu-latest

    needs: Bibop

    steps:
      - name: Code checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Check spec with Perfecto
        uses: essentialkaos/perfecto-action@v1
        with:
          files: mkcryptpasswd.spec

  Shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest

    needs: Bibop

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check scripts with Shellcheck
        uses: essentialkaos/shellcheck-action@v1
        with:
          files: install.sh SOURCES/mkcryptpasswd
